# Netlify configuration for SlackConnect Frontend
[build]
  publish = "out"
  command = "npm run build"

# Environment variables for production
[build.environment]
  NEXT_PUBLIC_BACKEND_URL = "https://slackconnectbackendv1.onrender.com/api"
  NEXT_PUBLIC_PRODUCTION_URL = "https://slackconnectfrontendv1.netlify.app"
  NETLIFY = "true"

# Redirect rules for SPA routing
[[redirects]]
  from = "/auth/*"
  to = "/auth/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and CORS
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
